version: '2'
services:
    hipsterapp-app:
        image: hipsterapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hipsterapp-mysql:3306/hipsterapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=hipsterapp-elasticsearch:9300
        ports:
            - 8080:8080
    hipsterapp-mysql:
        extends:
            file: mysql.yml
            service: hipsterapp-mysql
    hipsterapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hipsterapp-elasticsearch
